/**
 * Crossplay game configuration: board layout, tile values, and rules.
 * Direct port of crossplay_helper/config.py
 */

export const NONE = ".";
export const DL = "2L";
export const TL = "3L";
export const DW = "2W";
export const TW = "3W";
export const ST = "*";

export const BOARD_SIZE = 15;

export const BOARD_LAYOUT = [
  [TL,NONE,NONE,TW,NONE,NONE,NONE,DL,NONE,NONE,NONE,TW,NONE,NONE,TL],
  [NONE,DW,NONE,NONE,NONE,NONE,TL,NONE,TL,NONE,NONE,NONE,NONE,DW,NONE],
  [NONE,NONE,NONE,NONE,DL,NONE,NONE,NONE,NONE,NONE,DL,NONE,NONE,NONE,NONE],
  [TW,NONE,NONE,DL,NONE,NONE,NONE,DW,NONE,NONE,NONE,DL,NONE,NONE,TW],
  [NONE,NONE,DL,NONE,NONE,TL,NONE,NONE,NONE,TL,NONE,NONE,DL,NONE,NONE],
  [NONE,NONE,NONE,NONE,TL,NONE,NONE,DL,NONE,NONE,TL,NONE,NONE,NONE,NONE],
  [NONE,TL,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,TL,NONE],
  [DL,NONE,NONE,DW,NONE,DL,NONE,ST,NONE,DL,NONE,DW,NONE,NONE,DL],
  [NONE,TL,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,TL,NONE],
  [NONE,NONE,NONE,NONE,TL,NONE,NONE,DL,NONE,NONE,TL,NONE,NONE,NONE,NONE],
  [NONE,NONE,DL,NONE,NONE,TL,NONE,NONE,NONE,TL,NONE,NONE,DL,NONE,NONE],
  [TW,NONE,NONE,DL,NONE,NONE,NONE,DW,NONE,NONE,NONE,DL,NONE,NONE,TW],
  [NONE,NONE,NONE,NONE,DL,NONE,NONE,NONE,NONE,NONE,DL,NONE,NONE,NONE,NONE],
  [NONE,DW,NONE,NONE,NONE,NONE,TL,NONE,TL,NONE,NONE,NONE,NONE,DW,NONE],
  [TL,NONE,NONE,TW,NONE,NONE,NONE,DL,NONE,NONE,NONE,TW,NONE,NONE,TL],
];

export const CENTER = [7, 7];

export const TILE_VALUES = {
  A:1, B:4, C:3, D:2, E:1, F:4, G:4,
  H:3, I:1, J:10, K:6, L:2, M:3, N:1,
  O:1, P:3, Q:10, R:1, S:1, T:1, U:2,
  V:6, W:5, X:8, Y:4, Z:10, '?':0,
};

export const TILE_COUNTS = {
  A:9, B:2, C:2, D:4, E:12, F:2, G:3,
  H:3, I:8, J:1, K:1, L:4, M:2, N:5,
  O:8, P:2, Q:1, R:6, S:5, T:6, U:3,
  V:2, W:2, X:1, Y:2, Z:1, '?':3,
};

export const RACK_SIZE = 7;
export const BINGO_BONUS = 40;
export const CENTER_DOUBLES = false;

export const LETTER_MULTIPLIER = {
  [NONE]:1, [ST]:1, [DL]:2, [TL]:3, [DW]:1, [TW]:1,
};
export const WORD_MULTIPLIER = {
  [NONE]:1, [ST]:1, [DL]:1, [TL]:1, [DW]:2, [TW]:3,
};
